server:
  port: 8080

mybatis:
  configuration:
    map-underscore-to-camel-case: true  # 开启下划线到驼峰转换

  # 配置mybatis配置文件路径
  # config-location:
  mapper-locations: classpath:mapper/*Mapper.xml
  # 配置xml映射文件中的实体别名路径
  type-aliases-package: edu.hufe.entity

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/free_music?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    # 数据源类型
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      # 初始化大小
      initialSize: 5
      # 最小空闲数
      minIdle: 5
      # 最大连接数
      maxActive: 10
      # 最长等待时间
      maxWait: 60000

  redis:
    host: localhost
    port: 6379
    password:
    timeout: 5000ms

  resources:
    static-locations: classpath:templates/

  mvc:
    view:
      prefix: /
      suffix: .html
    servlet:
      # 服务器启动时创建servlet
      load-on-startup: 1

##    static-path-pattern: /*